[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "8bLNBctXqJMeouxAtMcT2qojhLT5nd89wiK4niWR4oFh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/amm.ts"
