[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q3_2024 = "5N33BWZRjgQhGCamDsx3pPsgBb5o54APDcvYCsTGQ1bp"

# anchor_vault_q3_2024 = "ETV7Mhe5HtsJu2i9tgRRe41NGZBPNZohdj8L2P3scfik"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/solix.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
